name: drnk
description: Track your alcohol consumption with ease. Featuring intuitive BAC calculations and time-to-sober estimates.
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.12
  get: ^4.6.1
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/welcome/
    - lib/assets/add/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
